### ISSUE TITLE
sed ubuntu14.04

### ISSUE THREAD

**Issue by leemoispace** [AndorChen/rbenv-china-mirror#2]
lee@ubuntu:~/.rbenv/versions$ rbenv install 2.1.2
sed: 无法读取 s!http://cache.ruby-lang.org/pub!https://ruby.taobao.org/mirrors!: 没有那个文件或目录

**Comment by AndorChen** [comment]
更新了一下，执行 `git pull` 命令，然后再试试。

**Comment by smilingsun** [comment]
Ubuntu 15.04 x64 Server，执行``rbenv install 2.2.3``，
结果还是不行，git pull了也不行

```
sed: can't read s!http://cache.ruby-lang.org/pub!https://ruby.taobao.org/mirrors!: No such file or directory
```

**Comment by AndorChen** [comment]
我想可能有两个问题：

1. ruby-build 中原来的下载地址已经由 `http` 变成了 `https`；
2. sed 在 Mac OS X 和 Ubuntu 中有差异。

现在，我把 sed 换成了 perl，请 @leemoispace 和 @smilingsun 再试试。我在 Yosemite 上测试通过。

重试之前，确保要升级 rbenv，ruby-build 和这个插件，因为这个插件之前的版本可能错误修改了 ruby-build 的定义文件。
