### ISSUE TITLE
rbenv 1.0.0 下面无法工作

### ISSUE THREAD

**Issue by huacnlee** [AndorChen/rbenv-china-mirror#6]
``` bash
$ rbenv install 2.3.1
ruby-build: definition not found: /Users/jason/.rbenv/plugins/ruby-build/share/ruby-build/2.3.1
```

我是用 Homebrew 安装的 rbenv

**Comment by AndorChen** [comment]
ruby-build 提示没有找到 2.3.1 的定义文件，升级 ruby-build 后再试试。

**Comment by AndorChen** [comment]
请忽略上一条。

目前的实现把 ruby-build 的路径写死了，所以找不到使用 homebrew 安装的 ruby-build（随 rbenv 一起安装）。

我做了 hotfix，你试试：https://github.com/AndorChen/rbenv-china-mirror/tree/hotfix
