### ISSUE TITLE
无法安装，提示 ruby-build: definition not found

### ISSUE THREAD

**Issue by lgn21st** [AndorChen/rbenv-china-mirror#8]
不知道是不是 ruby-build 升级的缘故，今天早上尝试并提示错误信息

```
~ $ rbenv install 2.3.1
ruby-build: definition not found: /Users/Daniel/.rbenv/plugins/ruby-build/share/ruby-build/2.3.1
```

**Comment by lgn21st** [comment]
忘记说明了，我的 ruby-build 也是通过 brew 安装的。

**Comment by AndorChen** [comment]
同 [issue 6](https://github.com/AndorChen/rbenv-china-mirror/issues/6)

试试 hotfix 分支

**Comment by lgn21st** [comment]
我没有尝试 hotfix 分支，我发现解决办法也不难，就是不用 brew install ruby-build，而是直接把 ruby-build clone 到 .rbenv/plugins 目录下，就正常了。

**Comment by AndorChen** [comment]
@lgn21st 是的，之前是直接在 `~/.rbenv` 的插件目录下搜索定义文件，后来 @huacnlee 反馈，我改了搜索定义文件的方式，放在 hotfix 分支中，因为他没有给我反馈，所以还没合并在主分支。

**Comment by huacnlee** [comment]
我没用 rbenv 没法反馈
Andor Chen <notifications@github.com>于2016年9月17日 周六上午9:41写道：
